// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF_npqtAj81cS1SNqrN4RI4QC_P5DBsX0',
    appId: '1:129824840759:web:27e518735981bd3a7973b2',
    messagingSenderId: '129824840759',
    projectId: 'complaint-management-sys-9d4b3',
    authDomain: 'complaint-management-sys-9d4b3.firebaseapp.com',
    storageBucket: 'complaint-management-sys-9d4b3.appspot.com',
    measurementId: 'G-BCGXS30L4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYWCIrVK-kgoWrm-0k90ec3eU-3wiM_yA',
    appId: '1:129824840759:android:e73c959061452a5a7973b2',
    messagingSenderId: '129824840759',
    projectId: 'complaint-management-sys-9d4b3',
    storageBucket: 'complaint-management-sys-9d4b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN4ix0xysP6ulPbaaQC0ZkR_6pBct67o8',
    appId: '1:129824840759:ios:29eff907591dc1ad7973b2',
    messagingSenderId: '129824840759',
    projectId: 'complaint-management-sys-9d4b3',
    storageBucket: 'complaint-management-sys-9d4b3.appspot.com',
    iosClientId: '129824840759-623i7m2qfaj85o8uqrr4910tbd6cjg4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.complaintManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN4ix0xysP6ulPbaaQC0ZkR_6pBct67o8',
    appId: '1:129824840759:ios:29eff907591dc1ad7973b2',
    messagingSenderId: '129824840759',
    projectId: 'complaint-management-sys-9d4b3',
    storageBucket: 'complaint-management-sys-9d4b3.appspot.com',
    iosClientId: '129824840759-623i7m2qfaj85o8uqrr4910tbd6cjg4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.complaintManagementApp',
  );
}
